"""Add photo fields to Solicitud model

Revision ID: 00956a47a013
Revises: 1c1d49d2f5be
Create Date: 2025-03-18 10:42:48.989878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00956a47a013'
down_revision = '1c1d49d2f5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('foto2', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('foto2')
        batch_op.drop_column('foto1')

    # ### end Alembic commands ###
