"""Add financial and quote fields to Solicitud model

Revision ID: 1c1d49d2f5be
Revises: f739ba1029ed
Create Date: 2025-03-18 08:59:46.604725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1d49d2f5be'
down_revision = 'f739ba1029ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_solicitado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monto_aprobado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('realizado_por', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('realizado_por')
        batch_op.drop_column('monto_aprobado')
        batch_op.drop_column('monto_solicitado')

    # ### end Alembic commands ###
