"""Add community and source fields to Solicitud model

Revision ID: f739ba1029ed
Revises: f4f32831fe49
Create Date: 2025-03-17 20:45:17.473537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f739ba1029ed'
down_revision = 'f4f32831fe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comunidad', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('fuente', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('fuente')
        batch_op.drop_column('comunidad')

    # ### end Alembic commands ###
